# Generated by Django 3.2 on 2022-11-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_auto_20221109_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_year',
            field=models.DateField(verbose_name='date birth'),
        ),
    ]
