# Generated by Django 3.2 on 2022-11-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_alter_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='sum',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Loans'),
        ),
    ]
